name: Cypress Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 13 * * 0"
jobs:
  build:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: npm install and test
        run: |
          npm install
          npm run test:parallel

      - name: Upload screenshots
        uses: actions/upload-artifact@v3.1.3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
